/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 25
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_package_line = 1,
  sym_section_header = 2,
  sym_func_line = 3,
  aux_sym_func_block_token1 = 4,
  aux_sym_func_block_token2 = 5,
  aux_sym_func_block_token3 = 6,
  aux_sym_func_block_token4 = 7,
  aux_sym_func_block_token5 = 8,
  aux_sym_var_block_token1 = 9,
  aux_sym_var_block_token2 = 10,
  aux_sym_var_block_token3 = 11,
  sym_var_line = 12,
  aux_sym_const_block_token1 = 13,
  sym_const_line = 14,
  aux_sym_type_block_token1 = 15,
  sym_type_line = 16,
  sym_text_line = 17,
  sym_document = 18,
  sym_func_block = 19,
  sym_var_block = 20,
  sym_const_block = 21,
  sym_type_block = 22,
  aux_sym_document_repeat1 = 23,
  aux_sym_func_block_repeat1 = 24,
  aux_sym_var_block_repeat1 = 25,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_package_line] = "package_line",
  [sym_section_header] = "section_header",
  [sym_func_line] = "func_line",
  [aux_sym_func_block_token1] = "func_block_token1",
  [aux_sym_func_block_token2] = "func_block_token2",
  [aux_sym_func_block_token3] = "func_block_token3",
  [aux_sym_func_block_token4] = "func_block_token4",
  [aux_sym_func_block_token5] = "func_block_token5",
  [aux_sym_var_block_token1] = "var_block_token1",
  [aux_sym_var_block_token2] = "var_block_token2",
  [aux_sym_var_block_token3] = "var_block_token3",
  [sym_var_line] = "var_line",
  [aux_sym_const_block_token1] = "const_block_token1",
  [sym_const_line] = "const_line",
  [aux_sym_type_block_token1] = "type_block_token1",
  [sym_type_line] = "type_line",
  [sym_text_line] = "text_line",
  [sym_document] = "document",
  [sym_func_block] = "func_block",
  [sym_var_block] = "var_block",
  [sym_const_block] = "const_block",
  [sym_type_block] = "type_block",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_func_block_repeat1] = "func_block_repeat1",
  [aux_sym_var_block_repeat1] = "var_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_package_line] = sym_package_line,
  [sym_section_header] = sym_section_header,
  [sym_func_line] = sym_func_line,
  [aux_sym_func_block_token1] = aux_sym_func_block_token1,
  [aux_sym_func_block_token2] = aux_sym_func_block_token2,
  [aux_sym_func_block_token3] = aux_sym_func_block_token3,
  [aux_sym_func_block_token4] = aux_sym_func_block_token4,
  [aux_sym_func_block_token5] = aux_sym_func_block_token5,
  [aux_sym_var_block_token1] = aux_sym_var_block_token1,
  [aux_sym_var_block_token2] = aux_sym_var_block_token2,
  [aux_sym_var_block_token3] = aux_sym_var_block_token3,
  [sym_var_line] = sym_var_line,
  [aux_sym_const_block_token1] = aux_sym_const_block_token1,
  [sym_const_line] = sym_const_line,
  [aux_sym_type_block_token1] = aux_sym_type_block_token1,
  [sym_type_line] = sym_type_line,
  [sym_text_line] = sym_text_line,
  [sym_document] = sym_document,
  [sym_func_block] = sym_func_block,
  [sym_var_block] = sym_var_block,
  [sym_const_block] = sym_const_block,
  [sym_type_block] = sym_type_block,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_func_block_repeat1] = aux_sym_func_block_repeat1,
  [aux_sym_var_block_repeat1] = aux_sym_var_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_package_line] = {
    .visible = true,
    .named = true,
  },
  [sym_section_header] = {
    .visible = true,
    .named = true,
  },
  [sym_func_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_func_block_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_func_block_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_func_block_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_func_block_token4] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_func_block_token5] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_var_block_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_var_block_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_var_block_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_var_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_const_block_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_const_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_type_block_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_type_line] = {
    .visible = true,
    .named = true,
  },
  [sym_text_line] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_func_block] = {
    .visible = true,
    .named = true,
  },
  [sym_var_block] = {
    .visible = true,
    .named = true,
  },
  [sym_const_block] = {
    .visible = true,
    .named = true,
  },
  [sym_type_block] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_func_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_var_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(83);
      ADVANCE_MAP(
        ')', 104,
        'C', 31,
        'D', 20,
        'F', 43,
        'T', 44,
        'V', 12,
        'c', 64,
        'f', 74,
        'p', 45,
        't', 76,
        'v', 46,
        '}', 99,
        '\t', 11,
        ' ', 11,
      );
      if (('\n' <= lookahead && lookahead <= '\r')) SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(1);
      if (lookahead == '(') ADVANCE(100);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(2);
      if (lookahead == '{') ADVANCE(91);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(87);
      if (lookahead != 0) ADVANCE(89);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == ')') ADVANCE(104);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(3);
      if ((0x0b <= lookahead && lookahead <= '\r')) SKIP(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(103);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(96);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(95);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '(') ADVANCE(107);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(110);
      if (lookahead != 0) ADVANCE(111);
      END_STATE();
    case 8:
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '}') ADVANCE(99);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(8);
      if ((0x0b <= lookahead && lookahead <= '\r')) SKIP(8);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 9:
      if (lookahead == '(') ADVANCE(100);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(1);
      END_STATE();
    case 10:
      if (lookahead == '(') ADVANCE(107);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(7);
      END_STATE();
    case 11:
      ADVANCE_MAP(
        ')', 104,
        'C', 31,
        'D', 20,
        'F', 43,
        'T', 44,
        'V', 12,
        'c', 64,
        'f', 74,
        'p', 45,
        't', 76,
        'v', 46,
        '}', 99,
        '\t', 11,
        ' ', 11,
      );
      if (('\n' <= lookahead && lookahead <= '\r')) SKIP(11);
      END_STATE();
    case 12:
      if (lookahead == 'A') ADVANCE(35);
      END_STATE();
    case 13:
      if (lookahead == 'A') ADVANCE(16);
      END_STATE();
    case 14:
      if (lookahead == 'A') ADVANCE(30);
      END_STATE();
    case 15:
      if (lookahead == 'A') ADVANCE(42);
      END_STATE();
    case 16:
      if (lookahead == 'B') ADVANCE(26);
      END_STATE();
    case 17:
      if (lookahead == 'C') ADVANCE(40);
      END_STATE();
    case 18:
      if (lookahead == 'C') ADVANCE(15);
      END_STATE();
    case 19:
      if (lookahead == 'D') ADVANCE(85);
      END_STATE();
    case 20:
      if (lookahead == 'E') ADVANCE(34);
      END_STATE();
    case 21:
      if (lookahead == 'E') ADVANCE(19);
      END_STATE();
    case 22:
      if (lookahead == 'E') ADVANCE(38);
      END_STATE();
    case 23:
      if (lookahead == 'E') ADVANCE(18);
      END_STATE();
    case 24:
      if (lookahead == 'I') ADVANCE(13);
      END_STATE();
    case 25:
      if (lookahead == 'I') ADVANCE(32);
      END_STATE();
    case 26:
      if (lookahead == 'L') ADVANCE(22);
      END_STATE();
    case 27:
      if (lookahead == 'N') ADVANCE(37);
      END_STATE();
    case 28:
      if (lookahead == 'N') ADVANCE(17);
      END_STATE();
    case 29:
      if (lookahead == 'N') ADVANCE(38);
      END_STATE();
    case 30:
      if (lookahead == 'N') ADVANCE(39);
      END_STATE();
    case 31:
      if (lookahead == 'O') ADVANCE(27);
      END_STATE();
    case 32:
      if (lookahead == 'O') ADVANCE(29);
      END_STATE();
    case 33:
      if (lookahead == 'P') ADVANCE(22);
      END_STATE();
    case 34:
      if (lookahead == 'P') ADVANCE(36);
      END_STATE();
    case 35:
      if (lookahead == 'R') ADVANCE(24);
      END_STATE();
    case 36:
      if (lookahead == 'R') ADVANCE(23);
      END_STATE();
    case 37:
      if (lookahead == 'S') ADVANCE(41);
      END_STATE();
    case 38:
      if (lookahead == 'S') ADVANCE(85);
      END_STATE();
    case 39:
      if (lookahead == 'T') ADVANCE(38);
      END_STATE();
    case 40:
      if (lookahead == 'T') ADVANCE(25);
      END_STATE();
    case 41:
      if (lookahead == 'T') ADVANCE(14);
      END_STATE();
    case 42:
      if (lookahead == 'T') ADVANCE(21);
      END_STATE();
    case 43:
      if (lookahead == 'U') ADVANCE(28);
      END_STATE();
    case 44:
      if (lookahead == 'Y') ADVANCE(33);
      END_STATE();
    case 45:
      if (lookahead == 'a') ADVANCE(49);
      END_STATE();
    case 46:
      if (lookahead == 'a') ADVANCE(66);
      END_STATE();
    case 47:
      if (lookahead == 'a') ADVANCE(58);
      END_STATE();
    case 48:
      if (lookahead == 'a') ADVANCE(51);
      END_STATE();
    case 49:
      if (lookahead == 'c') ADVANCE(60);
      END_STATE();
    case 50:
      if (lookahead == 'c') ADVANCE(79);
      END_STATE();
    case 51:
      if (lookahead == 'c') ADVANCE(55);
      END_STATE();
    case 52:
      if (lookahead == 'c') ADVANCE(70);
      END_STATE();
    case 53:
      if (lookahead == 'e') ADVANCE(115);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(84);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(78);
      END_STATE();
    case 56:
      if (lookahead == 'e') ADVANCE(67);
      END_STATE();
    case 57:
      if (lookahead == 'f') ADVANCE(48);
      END_STATE();
    case 58:
      if (lookahead == 'g') ADVANCE(54);
      END_STATE();
    case 59:
      if (lookahead == 'i') ADVANCE(63);
      if (lookahead == 's') ADVANCE(71);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(59);
      END_STATE();
    case 60:
      if (lookahead == 'k') ADVANCE(47);
      END_STATE();
    case 61:
      if (lookahead == 'n') ADVANCE(69);
      END_STATE();
    case 62:
      if (lookahead == 'n') ADVANCE(50);
      END_STATE();
    case 63:
      if (lookahead == 'n') ADVANCE(73);
      END_STATE();
    case 64:
      if (lookahead == 'o') ADVANCE(61);
      END_STATE();
    case 65:
      if (lookahead == 'p') ADVANCE(53);
      END_STATE();
    case 66:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 67:
      if (lookahead == 'r') ADVANCE(57);
      END_STATE();
    case 68:
      if (lookahead == 'r') ADVANCE(75);
      END_STATE();
    case 69:
      if (lookahead == 's') ADVANCE(72);
      END_STATE();
    case 70:
      if (lookahead == 't') ADVANCE(78);
      END_STATE();
    case 71:
      if (lookahead == 't') ADVANCE(68);
      END_STATE();
    case 72:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 73:
      if (lookahead == 't') ADVANCE(56);
      END_STATE();
    case 74:
      if (lookahead == 'u') ADVANCE(62);
      END_STATE();
    case 75:
      if (lookahead == 'u') ADVANCE(52);
      END_STATE();
    case 76:
      if (lookahead == 'y') ADVANCE(65);
      END_STATE();
    case 77:
      if (lookahead == '{') ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(77);
      END_STATE();
    case 78:
      if (lookahead == '{') ADVANCE(112);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(78);
      END_STATE();
    case 79:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      END_STATE();
    case 80:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 81:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 82:
      if (eof) ADVANCE(83);
      if (lookahead == '\n') SKIP(82);
      if (lookahead == 'C') ADVANCE(159);
      if (lookahead == 'D') ADVANCE(148);
      if (lookahead == 'F') ADVANCE(171);
      if (lookahead == 'T') ADVANCE(172);
      if (lookahead == 'V') ADVANCE(139);
      if (lookahead == 'c') ADVANCE(184);
      if (lookahead == 'f') ADVANCE(189);
      if (lookahead == 'p') ADVANCE(173);
      if (lookahead == 't') ADVANCE(190);
      if (lookahead == 'v') ADVANCE(174);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(144);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(144);
      if (lookahead != 0) ADVANCE(192);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_package_line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_section_header);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_section_header);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_func_line);
      if (lookahead == '\n') ADVANCE(2);
      if (lookahead == '{') ADVANCE(91);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(87);
      if (lookahead != 0) ADVANCE(89);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_func_line);
      if (lookahead == '\n') ADVANCE(2);
      if (lookahead == '{') ADVANCE(93);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(88);
      if (lookahead != 0) ADVANCE(90);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_func_line);
      if (lookahead == '{') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(89);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_func_line);
      if (lookahead == '{') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(90);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_func_block_token1);
      if (lookahead == '{') ADVANCE(89);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(77);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(89);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_func_block_token1);
      if (lookahead == '{') ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(77);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_func_block_token1);
      if (lookahead == '{') ADVANCE(90);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(191);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(90);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_func_block_token1);
      if (lookahead == '{') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(191);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_func_block_token2);
      if (lookahead == '\n') ADVANCE(95);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(6);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_func_block_token3);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_func_block_token4);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(3);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_func_block_token4);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(8);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym_func_block_token5);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym_var_block_token1);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym_var_block_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(106);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(aux_sym_var_block_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym_var_block_token2);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_var_block_token3);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_var_line);
      if (lookahead == '\n') ADVANCE(1);
      if (lookahead == '(') ADVANCE(101);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_var_line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(106);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(aux_sym_const_block_token1);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(aux_sym_const_block_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(111);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(aux_sym_const_block_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_const_line);
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '(') ADVANCE(108);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(110);
      if (lookahead != 0) ADVANCE(111);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_const_line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(111);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(aux_sym_type_block_token1);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(aux_sym_type_block_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(132);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == '\n') ADVANCE(80);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(114);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(117);
      if (lookahead != 0) ADVANCE(132);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == '\n') ADVANCE(80);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(114);
      if (lookahead != 0) ADVANCE(132);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == '\n') ADVANCE(59);
      if (lookahead == 'i') ADVANCE(125);
      if (lookahead == 's') ADVANCE(128);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(116);
      if (lookahead != 0) ADVANCE(132);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == '\n') ADVANCE(59);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(116);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(117);
      if (lookahead != 0) ADVANCE(132);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == '\n') ADVANCE(78);
      if (lookahead == '{') ADVANCE(113);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(118);
      if (lookahead != 0) ADVANCE(132);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == 'a') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(132);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == 'c') ADVANCE(122);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(132);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == 'c') ADVANCE(130);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(132);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == 'e') ADVANCE(118);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(132);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == 'e') ADVANCE(127);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(132);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == 'f') ADVANCE(119);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(132);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == 'n') ADVANCE(129);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(132);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == 'r') ADVANCE(131);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(132);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == 'r') ADVANCE(124);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(132);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == 't') ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(132);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == 't') ADVANCE(123);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(132);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == 't') ADVANCE(118);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(132);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == 'u') ADVANCE(121);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(132);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(132);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(1);
      if (lookahead == '(') ADVANCE(102);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(1);
      if (lookahead == '(') ADVANCE(102);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(133);
      if (lookahead != 0) ADVANCE(192);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(2);
      if (lookahead == '{') ADVANCE(93);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(88);
      if (lookahead != 0) ADVANCE(90);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(135);
      if (lookahead != 0) ADVANCE(192);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '(') ADVANCE(109);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(110);
      if (lookahead != 0) ADVANCE(111);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '(') ADVANCE(109);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(137);
      if (lookahead != 0) ADVANCE(192);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'A') ADVANCE(163);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'A') ADVANCE(143);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'A') ADVANCE(158);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'A') ADVANCE(170);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'B') ADVANCE(154);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_text_line);
      ADVANCE_MAP(
        'C', 159,
        'D', 148,
        'F', 171,
        'T', 172,
        'V', 139,
        'c', 184,
        'f', 189,
        'p', 173,
        't', 190,
        'v', 174,
        '\t', 144,
        ' ', 144,
      );
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(144);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(192);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'C') ADVANCE(168);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'C') ADVANCE(142);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'D') ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'E') ADVANCE(162);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'E') ADVANCE(147);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'E') ADVANCE(166);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'E') ADVANCE(146);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'I') ADVANCE(140);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'I') ADVANCE(160);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'L') ADVANCE(150);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'N') ADVANCE(165);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'N') ADVANCE(145);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'N') ADVANCE(166);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'N') ADVANCE(167);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'O') ADVANCE(155);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'O') ADVANCE(157);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'P') ADVANCE(150);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'P') ADVANCE(164);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'R') ADVANCE(152);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'R') ADVANCE(151);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'S') ADVANCE(169);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'S') ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'T') ADVANCE(166);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'T') ADVANCE(153);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'T') ADVANCE(141);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'T') ADVANCE(149);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'U') ADVANCE(156);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'Y') ADVANCE(161);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'a') ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'a') ADVANCE(186);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'a') ADVANCE(180);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'c') ADVANCE(181);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'c') ADVANCE(136);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'e') ADVANCE(115);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'e') ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'g') ADVANCE(179);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'k') ADVANCE(175);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'n') ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'n') ADVANCE(177);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'o') ADVANCE(182);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'p') ADVANCE(178);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'r') ADVANCE(134);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 's') ADVANCE(188);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 't') ADVANCE(138);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'u') ADVANCE(183);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'y') ADVANCE(185);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '{') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(191);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 82},
  [2] = {.lex_state = 82},
  [3] = {.lex_state = 82},
  [4] = {.lex_state = 82},
  [5] = {.lex_state = 82},
  [6] = {.lex_state = 82},
  [7] = {.lex_state = 82},
  [8] = {.lex_state = 82},
  [9] = {.lex_state = 82},
  [10] = {.lex_state = 82},
  [11] = {.lex_state = 82},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 8},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 8},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 8},
  [19] = {.lex_state = 8},
  [20] = {.lex_state = 8},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_package_line] = ACTIONS(1),
    [sym_section_header] = ACTIONS(1),
    [sym_func_line] = ACTIONS(1),
    [aux_sym_func_block_token1] = ACTIONS(1),
    [aux_sym_func_block_token5] = ACTIONS(1),
    [aux_sym_var_block_token1] = ACTIONS(1),
    [aux_sym_var_block_token3] = ACTIONS(1),
    [sym_var_line] = ACTIONS(1),
    [aux_sym_const_block_token1] = ACTIONS(1),
    [sym_const_line] = ACTIONS(1),
    [aux_sym_type_block_token1] = ACTIONS(1),
    [sym_type_line] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(24),
    [sym_func_block] = STATE(2),
    [sym_var_block] = STATE(2),
    [sym_const_block] = STATE(2),
    [sym_type_block] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_package_line] = ACTIONS(5),
    [sym_section_header] = ACTIONS(5),
    [sym_func_line] = ACTIONS(5),
    [aux_sym_func_block_token1] = ACTIONS(7),
    [aux_sym_var_block_token1] = ACTIONS(9),
    [sym_var_line] = ACTIONS(5),
    [aux_sym_const_block_token1] = ACTIONS(11),
    [sym_const_line] = ACTIONS(5),
    [aux_sym_type_block_token1] = ACTIONS(13),
    [sym_type_line] = ACTIONS(5),
    [sym_text_line] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym_func_block] = STATE(3),
    [sym_var_block] = STATE(3),
    [sym_const_block] = STATE(3),
    [sym_type_block] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_package_line] = ACTIONS(17),
    [sym_section_header] = ACTIONS(17),
    [sym_func_line] = ACTIONS(17),
    [aux_sym_func_block_token1] = ACTIONS(7),
    [aux_sym_var_block_token1] = ACTIONS(9),
    [sym_var_line] = ACTIONS(17),
    [aux_sym_const_block_token1] = ACTIONS(11),
    [sym_const_line] = ACTIONS(17),
    [aux_sym_type_block_token1] = ACTIONS(13),
    [sym_type_line] = ACTIONS(17),
    [sym_text_line] = ACTIONS(17),
  },
  [STATE(3)] = {
    [sym_func_block] = STATE(3),
    [sym_var_block] = STATE(3),
    [sym_const_block] = STATE(3),
    [sym_type_block] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_package_line] = ACTIONS(21),
    [sym_section_header] = ACTIONS(21),
    [sym_func_line] = ACTIONS(21),
    [aux_sym_func_block_token1] = ACTIONS(24),
    [aux_sym_var_block_token1] = ACTIONS(27),
    [sym_var_line] = ACTIONS(21),
    [aux_sym_const_block_token1] = ACTIONS(30),
    [sym_const_line] = ACTIONS(21),
    [aux_sym_type_block_token1] = ACTIONS(33),
    [sym_type_line] = ACTIONS(21),
    [sym_text_line] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(36), 1,
      ts_builtin_sym_end,
    ACTIONS(38), 11,
      sym_package_line,
      sym_section_header,
      sym_func_line,
      aux_sym_func_block_token1,
      aux_sym_var_block_token1,
      sym_var_line,
      aux_sym_const_block_token1,
      sym_const_line,
      aux_sym_type_block_token1,
      sym_type_line,
      sym_text_line,
  [17] = 2,
    ACTIONS(40), 1,
      ts_builtin_sym_end,
    ACTIONS(42), 11,
      sym_package_line,
      sym_section_header,
      sym_func_line,
      aux_sym_func_block_token1,
      aux_sym_var_block_token1,
      sym_var_line,
      aux_sym_const_block_token1,
      sym_const_line,
      aux_sym_type_block_token1,
      sym_type_line,
      sym_text_line,
  [34] = 2,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    ACTIONS(46), 11,
      sym_package_line,
      sym_section_header,
      sym_func_line,
      aux_sym_func_block_token1,
      aux_sym_var_block_token1,
      sym_var_line,
      aux_sym_const_block_token1,
      sym_const_line,
      aux_sym_type_block_token1,
      sym_type_line,
      sym_text_line,
  [51] = 2,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
    ACTIONS(50), 11,
      sym_package_line,
      sym_section_header,
      sym_func_line,
      aux_sym_func_block_token1,
      aux_sym_var_block_token1,
      sym_var_line,
      aux_sym_const_block_token1,
      sym_const_line,
      aux_sym_type_block_token1,
      sym_type_line,
      sym_text_line,
  [68] = 2,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    ACTIONS(54), 11,
      sym_package_line,
      sym_section_header,
      sym_func_line,
      aux_sym_func_block_token1,
      aux_sym_var_block_token1,
      sym_var_line,
      aux_sym_const_block_token1,
      sym_const_line,
      aux_sym_type_block_token1,
      sym_type_line,
      sym_text_line,
  [85] = 2,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    ACTIONS(58), 11,
      sym_package_line,
      sym_section_header,
      sym_func_line,
      aux_sym_func_block_token1,
      aux_sym_var_block_token1,
      sym_var_line,
      aux_sym_const_block_token1,
      sym_const_line,
      aux_sym_type_block_token1,
      sym_type_line,
      sym_text_line,
  [102] = 2,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    ACTIONS(62), 11,
      sym_package_line,
      sym_section_header,
      sym_func_line,
      aux_sym_func_block_token1,
      aux_sym_var_block_token1,
      sym_var_line,
      aux_sym_const_block_token1,
      sym_const_line,
      aux_sym_type_block_token1,
      sym_type_line,
      sym_text_line,
  [119] = 2,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
    ACTIONS(66), 11,
      sym_package_line,
      sym_section_header,
      sym_func_line,
      aux_sym_func_block_token1,
      aux_sym_var_block_token1,
      sym_var_line,
      aux_sym_const_block_token1,
      sym_const_line,
      aux_sym_type_block_token1,
      sym_type_line,
      sym_text_line,
  [136] = 4,
    ACTIONS(68), 1,
      aux_sym_func_block_token4,
    ACTIONS(70), 1,
      aux_sym_var_block_token2,
    ACTIONS(72), 1,
      aux_sym_var_block_token3,
    STATE(21), 1,
      aux_sym_var_block_repeat1,
  [149] = 4,
    ACTIONS(74), 1,
      aux_sym_func_block_token4,
    ACTIONS(76), 1,
      aux_sym_var_block_token2,
    ACTIONS(78), 1,
      aux_sym_var_block_token3,
    STATE(15), 1,
      aux_sym_var_block_repeat1,
  [162] = 4,
    ACTIONS(80), 1,
      aux_sym_func_block_token3,
    ACTIONS(82), 1,
      aux_sym_func_block_token4,
    ACTIONS(84), 1,
      aux_sym_func_block_token5,
    STATE(16), 1,
      aux_sym_func_block_repeat1,
  [175] = 4,
    ACTIONS(86), 1,
      aux_sym_func_block_token4,
    ACTIONS(88), 1,
      aux_sym_var_block_token2,
    ACTIONS(90), 1,
      aux_sym_var_block_token3,
    STATE(17), 1,
      aux_sym_var_block_repeat1,
  [188] = 4,
    ACTIONS(92), 1,
      aux_sym_func_block_token3,
    ACTIONS(94), 1,
      aux_sym_func_block_token4,
    ACTIONS(96), 1,
      aux_sym_func_block_token5,
    STATE(20), 1,
      aux_sym_func_block_repeat1,
  [201] = 4,
    ACTIONS(98), 1,
      aux_sym_func_block_token4,
    ACTIONS(101), 1,
      aux_sym_var_block_token2,
    ACTIONS(104), 1,
      aux_sym_var_block_token3,
    STATE(17), 1,
      aux_sym_var_block_repeat1,
  [214] = 4,
    ACTIONS(92), 1,
      aux_sym_func_block_token3,
    ACTIONS(94), 1,
      aux_sym_func_block_token4,
    ACTIONS(106), 1,
      aux_sym_func_block_token5,
    STATE(20), 1,
      aux_sym_func_block_repeat1,
  [227] = 4,
    ACTIONS(108), 1,
      aux_sym_func_block_token3,
    ACTIONS(110), 1,
      aux_sym_func_block_token4,
    ACTIONS(112), 1,
      aux_sym_func_block_token5,
    STATE(18), 1,
      aux_sym_func_block_repeat1,
  [240] = 4,
    ACTIONS(114), 1,
      aux_sym_func_block_token3,
    ACTIONS(117), 1,
      aux_sym_func_block_token4,
    ACTIONS(120), 1,
      aux_sym_func_block_token5,
    STATE(20), 1,
      aux_sym_func_block_repeat1,
  [253] = 4,
    ACTIONS(86), 1,
      aux_sym_func_block_token4,
    ACTIONS(88), 1,
      aux_sym_var_block_token2,
    ACTIONS(122), 1,
      aux_sym_var_block_token3,
    STATE(17), 1,
      aux_sym_var_block_repeat1,
  [266] = 1,
    ACTIONS(124), 1,
      aux_sym_func_block_token2,
  [270] = 1,
    ACTIONS(126), 1,
      aux_sym_func_block_token2,
  [274] = 1,
    ACTIONS(128), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 17,
  [SMALL_STATE(6)] = 34,
  [SMALL_STATE(7)] = 51,
  [SMALL_STATE(8)] = 68,
  [SMALL_STATE(9)] = 85,
  [SMALL_STATE(10)] = 102,
  [SMALL_STATE(11)] = 119,
  [SMALL_STATE(12)] = 136,
  [SMALL_STATE(13)] = 149,
  [SMALL_STATE(14)] = 162,
  [SMALL_STATE(15)] = 175,
  [SMALL_STATE(16)] = 188,
  [SMALL_STATE(17)] = 201,
  [SMALL_STATE(18)] = 214,
  [SMALL_STATE(19)] = 227,
  [SMALL_STATE(20)] = 240,
  [SMALL_STATE(21)] = 253,
  [SMALL_STATE(22)] = 266,
  [SMALL_STATE(23)] = 270,
  [SMALL_STATE(24)] = 274,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_block, 2, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_block, 2, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_block, 2, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_const_block, 2, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_block, 4, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_block, 4, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_block, 4, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func_block, 4, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_block, 3, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func_block, 3, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_block, 3, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_block, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_block, 3, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_block, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_block, 3, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_const_block, 3, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_var_block_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [101] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_var_block_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_var_block_repeat1, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [114] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_func_block_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_func_block_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_func_block_repeat1, 2, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [128] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_godoc(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "godoc",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
