/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 26
#define LARGE_STATE_COUNT 13
#define SYMBOL_COUNT 31
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_package_line = 1,
  anon_sym_VARIABLES = 2,
  anon_sym_FUNCTIONS = 3,
  anon_sym_TYPES = 4,
  anon_sym_CONSTANTS = 5,
  anon_sym_DEPRECATED = 6,
  sym_func_line = 7,
  aux_sym_func_block_token1 = 8,
  aux_sym_func_block_token2 = 9,
  aux_sym_func_block_token3 = 10,
  aux_sym_func_block_token4 = 11,
  anon_sym_RBRACE = 12,
  aux_sym_var_block_token1 = 13,
  aux_sym_var_block_token2 = 14,
  anon_sym_RPAREN = 15,
  sym_var_line = 16,
  aux_sym_const_block_token1 = 17,
  sym_const_line = 18,
  aux_sym_type_block_token1 = 19,
  sym_type_line = 20,
  sym_text_line = 21,
  sym_document = 22,
  sym_section_header = 23,
  sym_func_block = 24,
  sym_var_block = 25,
  sym_const_block = 26,
  sym_type_block = 27,
  aux_sym_document_repeat1 = 28,
  aux_sym_func_block_repeat1 = 29,
  aux_sym_var_block_repeat1 = 30,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_package_line] = "package_line",
  [anon_sym_VARIABLES] = "VARIABLES",
  [anon_sym_FUNCTIONS] = "FUNCTIONS",
  [anon_sym_TYPES] = "TYPES",
  [anon_sym_CONSTANTS] = "CONSTANTS",
  [anon_sym_DEPRECATED] = "DEPRECATED",
  [sym_func_line] = "func_line",
  [aux_sym_func_block_token1] = "func_block_token1",
  [aux_sym_func_block_token2] = "func_block_token2",
  [aux_sym_func_block_token3] = "func_block_token3",
  [aux_sym_func_block_token4] = "func_block_token4",
  [anon_sym_RBRACE] = "}",
  [aux_sym_var_block_token1] = "var_block_token1",
  [aux_sym_var_block_token2] = "var_block_token2",
  [anon_sym_RPAREN] = ")",
  [sym_var_line] = "var_line",
  [aux_sym_const_block_token1] = "const_block_token1",
  [sym_const_line] = "const_line",
  [aux_sym_type_block_token1] = "type_block_token1",
  [sym_type_line] = "type_line",
  [sym_text_line] = "text_line",
  [sym_document] = "document",
  [sym_section_header] = "section_header",
  [sym_func_block] = "func_block",
  [sym_var_block] = "var_block",
  [sym_const_block] = "const_block",
  [sym_type_block] = "type_block",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_func_block_repeat1] = "func_block_repeat1",
  [aux_sym_var_block_repeat1] = "var_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_package_line] = sym_package_line,
  [anon_sym_VARIABLES] = anon_sym_VARIABLES,
  [anon_sym_FUNCTIONS] = anon_sym_FUNCTIONS,
  [anon_sym_TYPES] = anon_sym_TYPES,
  [anon_sym_CONSTANTS] = anon_sym_CONSTANTS,
  [anon_sym_DEPRECATED] = anon_sym_DEPRECATED,
  [sym_func_line] = sym_func_line,
  [aux_sym_func_block_token1] = aux_sym_func_block_token1,
  [aux_sym_func_block_token2] = aux_sym_func_block_token2,
  [aux_sym_func_block_token3] = aux_sym_func_block_token3,
  [aux_sym_func_block_token4] = aux_sym_func_block_token4,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym_var_block_token1] = aux_sym_var_block_token1,
  [aux_sym_var_block_token2] = aux_sym_var_block_token2,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_var_line] = sym_var_line,
  [aux_sym_const_block_token1] = aux_sym_const_block_token1,
  [sym_const_line] = sym_const_line,
  [aux_sym_type_block_token1] = aux_sym_type_block_token1,
  [sym_type_line] = sym_type_line,
  [sym_text_line] = sym_text_line,
  [sym_document] = sym_document,
  [sym_section_header] = sym_section_header,
  [sym_func_block] = sym_func_block,
  [sym_var_block] = sym_var_block,
  [sym_const_block] = sym_const_block,
  [sym_type_block] = sym_type_block,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_func_block_repeat1] = aux_sym_func_block_repeat1,
  [aux_sym_var_block_repeat1] = aux_sym_var_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_package_line] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_VARIABLES] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FUNCTIONS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TYPES] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CONSTANTS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DEPRECATED] = {
    .visible = true,
    .named = false,
  },
  [sym_func_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_func_block_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_func_block_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_func_block_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_func_block_token4] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_var_block_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_var_block_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_var_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_const_block_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_const_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_type_block_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_type_line] = {
    .visible = true,
    .named = true,
  },
  [sym_text_line] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_section_header] = {
    .visible = true,
    .named = true,
  },
  [sym_func_block] = {
    .visible = true,
    .named = true,
  },
  [sym_var_block] = {
    .visible = true,
    .named = true,
  },
  [sym_const_block] = {
    .visible = true,
    .named = true,
  },
  [sym_type_block] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_func_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_var_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(88);
      ADVANCE_MAP(
        ')', 117,
        'C', 33,
        'D', 21,
        'F', 48,
        'T', 49,
        'V', 13,
        'c', 69,
        'f', 79,
        'p', 50,
        't', 81,
        'v', 51,
        '}', 111,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(1);
      if (lookahead == '(') ADVANCE(113);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(119);
      if (lookahead != 0) ADVANCE(120);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(2);
      if (lookahead == '{') ADVANCE(104);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(100);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '}') ADVANCE(111);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(108);
      if (lookahead == '}') ADVANCE(112);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(107);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(116);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(106);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '(') ADVANCE(121);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(124);
      if (lookahead != 0) ADVANCE(125);
      END_STATE();
    case 9:
      if (lookahead == '\n') ADVANCE(110);
      if (lookahead == ')') ADVANCE(117);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(10);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 10:
      if (lookahead == '\n') ADVANCE(110);
      if (lookahead == ')') ADVANCE(118);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(10);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 11:
      if (lookahead == '(') ADVANCE(113);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(1);
      END_STATE();
    case 12:
      if (lookahead == '(') ADVANCE(121);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(8);
      END_STATE();
    case 13:
      if (lookahead == 'A') ADVANCE(37);
      END_STATE();
    case 14:
      if (lookahead == 'A') ADVANCE(17);
      END_STATE();
    case 15:
      if (lookahead == 'A') ADVANCE(31);
      END_STATE();
    case 16:
      if (lookahead == 'A') ADVANCE(47);
      END_STATE();
    case 17:
      if (lookahead == 'B') ADVANCE(28);
      END_STATE();
    case 18:
      if (lookahead == 'C') ADVANCE(44);
      END_STATE();
    case 19:
      if (lookahead == 'C') ADVANCE(16);
      END_STATE();
    case 20:
      if (lookahead == 'D') ADVANCE(98);
      END_STATE();
    case 21:
      if (lookahead == 'E') ADVANCE(36);
      END_STATE();
    case 22:
      if (lookahead == 'E') ADVANCE(20);
      END_STATE();
    case 23:
      if (lookahead == 'E') ADVANCE(40);
      END_STATE();
    case 24:
      if (lookahead == 'E') ADVANCE(19);
      END_STATE();
    case 25:
      if (lookahead == 'E') ADVANCE(43);
      END_STATE();
    case 26:
      if (lookahead == 'I') ADVANCE(14);
      END_STATE();
    case 27:
      if (lookahead == 'I') ADVANCE(34);
      END_STATE();
    case 28:
      if (lookahead == 'L') ADVANCE(25);
      END_STATE();
    case 29:
      if (lookahead == 'N') ADVANCE(39);
      END_STATE();
    case 30:
      if (lookahead == 'N') ADVANCE(18);
      END_STATE();
    case 31:
      if (lookahead == 'N') ADVANCE(46);
      END_STATE();
    case 32:
      if (lookahead == 'N') ADVANCE(42);
      END_STATE();
    case 33:
      if (lookahead == 'O') ADVANCE(29);
      END_STATE();
    case 34:
      if (lookahead == 'O') ADVANCE(32);
      END_STATE();
    case 35:
      if (lookahead == 'P') ADVANCE(23);
      END_STATE();
    case 36:
      if (lookahead == 'P') ADVANCE(38);
      END_STATE();
    case 37:
      if (lookahead == 'R') ADVANCE(26);
      END_STATE();
    case 38:
      if (lookahead == 'R') ADVANCE(24);
      END_STATE();
    case 39:
      if (lookahead == 'S') ADVANCE(45);
      END_STATE();
    case 40:
      if (lookahead == 'S') ADVANCE(94);
      END_STATE();
    case 41:
      if (lookahead == 'S') ADVANCE(96);
      END_STATE();
    case 42:
      if (lookahead == 'S') ADVANCE(92);
      END_STATE();
    case 43:
      if (lookahead == 'S') ADVANCE(90);
      END_STATE();
    case 44:
      if (lookahead == 'T') ADVANCE(27);
      END_STATE();
    case 45:
      if (lookahead == 'T') ADVANCE(15);
      END_STATE();
    case 46:
      if (lookahead == 'T') ADVANCE(41);
      END_STATE();
    case 47:
      if (lookahead == 'T') ADVANCE(22);
      END_STATE();
    case 48:
      if (lookahead == 'U') ADVANCE(30);
      END_STATE();
    case 49:
      if (lookahead == 'Y') ADVANCE(35);
      END_STATE();
    case 50:
      if (lookahead == 'a') ADVANCE(54);
      END_STATE();
    case 51:
      if (lookahead == 'a') ADVANCE(71);
      END_STATE();
    case 52:
      if (lookahead == 'a') ADVANCE(63);
      END_STATE();
    case 53:
      if (lookahead == 'a') ADVANCE(56);
      END_STATE();
    case 54:
      if (lookahead == 'c') ADVANCE(65);
      END_STATE();
    case 55:
      if (lookahead == 'c') ADVANCE(84);
      END_STATE();
    case 56:
      if (lookahead == 'c') ADVANCE(60);
      END_STATE();
    case 57:
      if (lookahead == 'c') ADVANCE(75);
      END_STATE();
    case 58:
      if (lookahead == 'e') ADVANCE(129);
      END_STATE();
    case 59:
      if (lookahead == 'e') ADVANCE(89);
      END_STATE();
    case 60:
      if (lookahead == 'e') ADVANCE(83);
      END_STATE();
    case 61:
      if (lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 62:
      if (lookahead == 'f') ADVANCE(53);
      END_STATE();
    case 63:
      if (lookahead == 'g') ADVANCE(59);
      END_STATE();
    case 64:
      if (lookahead == 'i') ADVANCE(68);
      if (lookahead == 's') ADVANCE(76);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(64);
      END_STATE();
    case 65:
      if (lookahead == 'k') ADVANCE(52);
      END_STATE();
    case 66:
      if (lookahead == 'n') ADVANCE(74);
      END_STATE();
    case 67:
      if (lookahead == 'n') ADVANCE(55);
      END_STATE();
    case 68:
      if (lookahead == 'n') ADVANCE(78);
      END_STATE();
    case 69:
      if (lookahead == 'o') ADVANCE(66);
      END_STATE();
    case 70:
      if (lookahead == 'p') ADVANCE(58);
      END_STATE();
    case 71:
      if (lookahead == 'r') ADVANCE(11);
      END_STATE();
    case 72:
      if (lookahead == 'r') ADVANCE(62);
      END_STATE();
    case 73:
      if (lookahead == 'r') ADVANCE(80);
      END_STATE();
    case 74:
      if (lookahead == 's') ADVANCE(77);
      END_STATE();
    case 75:
      if (lookahead == 't') ADVANCE(83);
      END_STATE();
    case 76:
      if (lookahead == 't') ADVANCE(73);
      END_STATE();
    case 77:
      if (lookahead == 't') ADVANCE(12);
      END_STATE();
    case 78:
      if (lookahead == 't') ADVANCE(61);
      END_STATE();
    case 79:
      if (lookahead == 'u') ADVANCE(67);
      END_STATE();
    case 80:
      if (lookahead == 'u') ADVANCE(57);
      END_STATE();
    case 81:
      if (lookahead == 'y') ADVANCE(70);
      END_STATE();
    case 82:
      if (lookahead == '{') ADVANCE(104);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(82);
      END_STATE();
    case 83:
      if (lookahead == '{') ADVANCE(126);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(83);
      END_STATE();
    case 84:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      END_STATE();
    case 85:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 86:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 87:
      if (eof) ADVANCE(88);
      if (lookahead == '\n') SKIP(87);
      if (lookahead == 'C') ADVANCE(174);
      if (lookahead == 'D') ADVANCE(162);
      if (lookahead == 'F') ADVANCE(189);
      if (lookahead == 'T') ADVANCE(190);
      if (lookahead == 'V') ADVANCE(153);
      if (lookahead == 'c') ADVANCE(202);
      if (lookahead == 'f') ADVANCE(207);
      if (lookahead == 'p') ADVANCE(191);
      if (lookahead == 't') ADVANCE(208);
      if (lookahead == 'v') ADVANCE(192);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(158);
      if (lookahead != 0) ADVANCE(210);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_package_line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(89);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_VARIABLES);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_VARIABLES);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_FUNCTIONS);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_FUNCTIONS);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_TYPES);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_TYPES);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_CONSTANTS);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_CONSTANTS);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_DEPRECATED);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_DEPRECATED);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_func_line);
      if (lookahead == '\n') ADVANCE(2);
      if (lookahead == '{') ADVANCE(104);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(100);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_func_line);
      if (lookahead == '\n') ADVANCE(2);
      if (lookahead == '{') ADVANCE(105);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(101);
      if (lookahead != 0) ADVANCE(103);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_func_line);
      if (lookahead == '{') ADVANCE(104);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_func_line);
      if (lookahead == '{') ADVANCE(105);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(103);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_func_block_token1);
      if (lookahead == '{') ADVANCE(104);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(82);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym_func_block_token1);
      if (lookahead == '{') ADVANCE(105);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(209);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(aux_sym_func_block_token2);
      if (lookahead == '\n') ADVANCE(106);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(7);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(aux_sym_func_block_token3);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(aux_sym_func_block_token3);
      if (lookahead == '\n') ADVANCE(108);
      if (lookahead == '}') ADVANCE(112);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(aux_sym_func_block_token4);
      if (lookahead == '\n') ADVANCE(108);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(4);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(aux_sym_func_block_token4);
      if (lookahead == '\n') ADVANCE(110);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(10);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      if (lookahead == '\n') ADVANCE(107);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(aux_sym_var_block_token1);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(aux_sym_var_block_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(120);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(aux_sym_var_block_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(aux_sym_var_block_token2);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      if (lookahead == '\n') ADVANCE(116);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_var_line);
      if (lookahead == '\n') ADVANCE(1);
      if (lookahead == '(') ADVANCE(114);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(119);
      if (lookahead != 0) ADVANCE(120);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_var_line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(120);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(aux_sym_const_block_token1);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(aux_sym_const_block_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(aux_sym_const_block_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_const_line);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '(') ADVANCE(122);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(124);
      if (lookahead != 0) ADVANCE(125);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_const_line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(aux_sym_type_block_token1);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(aux_sym_type_block_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == '\n') ADVANCE(85);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(128);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(131);
      if (lookahead != 0) ADVANCE(146);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == '\n') ADVANCE(85);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(128);
      if (lookahead != 0) ADVANCE(146);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead == 'i') ADVANCE(139);
      if (lookahead == 's') ADVANCE(142);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(130);
      if (lookahead != 0) ADVANCE(146);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == '\n') ADVANCE(64);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(130);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(131);
      if (lookahead != 0) ADVANCE(146);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == '\n') ADVANCE(83);
      if (lookahead == '{') ADVANCE(127);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(132);
      if (lookahead != 0) ADVANCE(146);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == 'a') ADVANCE(134);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == 'c') ADVANCE(136);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == 'c') ADVANCE(144);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == 'e') ADVANCE(132);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == 'e') ADVANCE(141);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == 'f') ADVANCE(133);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == 'n') ADVANCE(143);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == 'r') ADVANCE(145);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == 'r') ADVANCE(138);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == 't') ADVANCE(140);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == 't') ADVANCE(137);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == 't') ADVANCE(132);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead == 'u') ADVANCE(135);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_type_line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(1);
      if (lookahead == '(') ADVANCE(115);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(119);
      if (lookahead != 0) ADVANCE(120);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(1);
      if (lookahead == '(') ADVANCE(115);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(147);
      if (lookahead != 0) ADVANCE(210);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(2);
      if (lookahead == '{') ADVANCE(105);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(101);
      if (lookahead != 0) ADVANCE(103);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(149);
      if (lookahead != 0) ADVANCE(210);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '(') ADVANCE(123);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(124);
      if (lookahead != 0) ADVANCE(125);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '(') ADVANCE(123);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(151);
      if (lookahead != 0) ADVANCE(210);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'A') ADVANCE(178);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'A') ADVANCE(157);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'A') ADVANCE(172);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'A') ADVANCE(188);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'B') ADVANCE(169);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_text_line);
      ADVANCE_MAP(
        'C', 174,
        'D', 162,
        'F', 189,
        'T', 190,
        'V', 153,
        'c', 202,
        'f', 207,
        'p', 191,
        't', 208,
        'v', 192,
      );
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(158);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(210);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'C') ADVANCE(185);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'C') ADVANCE(156);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'D') ADVANCE(99);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'E') ADVANCE(177);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'E') ADVANCE(161);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'E') ADVANCE(181);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'E') ADVANCE(160);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'E') ADVANCE(184);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'I') ADVANCE(154);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'I') ADVANCE(175);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'L') ADVANCE(166);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'N') ADVANCE(180);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'N') ADVANCE(159);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'N') ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'N') ADVANCE(183);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'O') ADVANCE(170);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'O') ADVANCE(173);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'P') ADVANCE(164);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'P') ADVANCE(179);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'R') ADVANCE(167);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'R') ADVANCE(165);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'S') ADVANCE(186);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'S') ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'S') ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'S') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'S') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'T') ADVANCE(168);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'T') ADVANCE(155);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'T') ADVANCE(182);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'T') ADVANCE(163);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'U') ADVANCE(171);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'Y') ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'a') ADVANCE(194);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'a') ADVANCE(204);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'a') ADVANCE(198);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'c') ADVANCE(199);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 195:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'c') ADVANCE(150);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 196:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'e') ADVANCE(129);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 197:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'e') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 198:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'g') ADVANCE(197);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 199:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'k') ADVANCE(193);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 200:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'n') ADVANCE(205);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 201:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'n') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 202:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'o') ADVANCE(200);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 203:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'p') ADVANCE(196);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 204:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'r') ADVANCE(148);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 205:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 's') ADVANCE(206);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 206:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 't') ADVANCE(152);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 207:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'u') ADVANCE(201);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 208:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == 'y') ADVANCE(203);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 209:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '{') ADVANCE(105);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(209);
      END_STATE();
    case 210:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 87},
  [2] = {.lex_state = 87},
  [3] = {.lex_state = 87},
  [4] = {.lex_state = 87},
  [5] = {.lex_state = 87},
  [6] = {.lex_state = 87},
  [7] = {.lex_state = 87},
  [8] = {.lex_state = 87},
  [9] = {.lex_state = 87},
  [10] = {.lex_state = 87},
  [11] = {.lex_state = 87},
  [12] = {.lex_state = 87},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 9},
  [15] = {.lex_state = 9},
  [16] = {.lex_state = 9},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 9},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 9},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 7},
  [25] = {.lex_state = 7},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_package_line] = ACTIONS(1),
    [anon_sym_VARIABLES] = ACTIONS(1),
    [anon_sym_FUNCTIONS] = ACTIONS(1),
    [anon_sym_TYPES] = ACTIONS(1),
    [anon_sym_CONSTANTS] = ACTIONS(1),
    [anon_sym_DEPRECATED] = ACTIONS(1),
    [sym_func_line] = ACTIONS(1),
    [aux_sym_func_block_token1] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [aux_sym_var_block_token1] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_var_line] = ACTIONS(1),
    [aux_sym_const_block_token1] = ACTIONS(1),
    [sym_const_line] = ACTIONS(1),
    [aux_sym_type_block_token1] = ACTIONS(1),
    [sym_type_line] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(23),
    [sym_section_header] = STATE(2),
    [sym_func_block] = STATE(2),
    [sym_var_block] = STATE(2),
    [sym_const_block] = STATE(2),
    [sym_type_block] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_package_line] = ACTIONS(5),
    [anon_sym_VARIABLES] = ACTIONS(7),
    [anon_sym_FUNCTIONS] = ACTIONS(7),
    [anon_sym_TYPES] = ACTIONS(7),
    [anon_sym_CONSTANTS] = ACTIONS(7),
    [anon_sym_DEPRECATED] = ACTIONS(7),
    [sym_func_line] = ACTIONS(5),
    [aux_sym_func_block_token1] = ACTIONS(9),
    [aux_sym_var_block_token1] = ACTIONS(11),
    [sym_var_line] = ACTIONS(5),
    [aux_sym_const_block_token1] = ACTIONS(13),
    [sym_const_line] = ACTIONS(5),
    [aux_sym_type_block_token1] = ACTIONS(15),
    [sym_type_line] = ACTIONS(5),
    [sym_text_line] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym_section_header] = STATE(3),
    [sym_func_block] = STATE(3),
    [sym_var_block] = STATE(3),
    [sym_const_block] = STATE(3),
    [sym_type_block] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_package_line] = ACTIONS(19),
    [anon_sym_VARIABLES] = ACTIONS(7),
    [anon_sym_FUNCTIONS] = ACTIONS(7),
    [anon_sym_TYPES] = ACTIONS(7),
    [anon_sym_CONSTANTS] = ACTIONS(7),
    [anon_sym_DEPRECATED] = ACTIONS(7),
    [sym_func_line] = ACTIONS(19),
    [aux_sym_func_block_token1] = ACTIONS(9),
    [aux_sym_var_block_token1] = ACTIONS(11),
    [sym_var_line] = ACTIONS(19),
    [aux_sym_const_block_token1] = ACTIONS(13),
    [sym_const_line] = ACTIONS(19),
    [aux_sym_type_block_token1] = ACTIONS(15),
    [sym_type_line] = ACTIONS(19),
    [sym_text_line] = ACTIONS(19),
  },
  [STATE(3)] = {
    [sym_section_header] = STATE(3),
    [sym_func_block] = STATE(3),
    [sym_var_block] = STATE(3),
    [sym_const_block] = STATE(3),
    [sym_type_block] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_package_line] = ACTIONS(23),
    [anon_sym_VARIABLES] = ACTIONS(26),
    [anon_sym_FUNCTIONS] = ACTIONS(26),
    [anon_sym_TYPES] = ACTIONS(26),
    [anon_sym_CONSTANTS] = ACTIONS(26),
    [anon_sym_DEPRECATED] = ACTIONS(26),
    [sym_func_line] = ACTIONS(23),
    [aux_sym_func_block_token1] = ACTIONS(29),
    [aux_sym_var_block_token1] = ACTIONS(32),
    [sym_var_line] = ACTIONS(23),
    [aux_sym_const_block_token1] = ACTIONS(35),
    [sym_const_line] = ACTIONS(23),
    [aux_sym_type_block_token1] = ACTIONS(38),
    [sym_type_line] = ACTIONS(23),
    [sym_text_line] = ACTIONS(23),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(41),
    [sym_package_line] = ACTIONS(43),
    [anon_sym_VARIABLES] = ACTIONS(43),
    [anon_sym_FUNCTIONS] = ACTIONS(43),
    [anon_sym_TYPES] = ACTIONS(43),
    [anon_sym_CONSTANTS] = ACTIONS(43),
    [anon_sym_DEPRECATED] = ACTIONS(43),
    [sym_func_line] = ACTIONS(43),
    [aux_sym_func_block_token1] = ACTIONS(43),
    [aux_sym_var_block_token1] = ACTIONS(43),
    [sym_var_line] = ACTIONS(43),
    [aux_sym_const_block_token1] = ACTIONS(43),
    [sym_const_line] = ACTIONS(43),
    [aux_sym_type_block_token1] = ACTIONS(43),
    [sym_type_line] = ACTIONS(43),
    [sym_text_line] = ACTIONS(43),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(45),
    [sym_package_line] = ACTIONS(47),
    [anon_sym_VARIABLES] = ACTIONS(47),
    [anon_sym_FUNCTIONS] = ACTIONS(47),
    [anon_sym_TYPES] = ACTIONS(47),
    [anon_sym_CONSTANTS] = ACTIONS(47),
    [anon_sym_DEPRECATED] = ACTIONS(47),
    [sym_func_line] = ACTIONS(47),
    [aux_sym_func_block_token1] = ACTIONS(47),
    [aux_sym_var_block_token1] = ACTIONS(47),
    [sym_var_line] = ACTIONS(47),
    [aux_sym_const_block_token1] = ACTIONS(47),
    [sym_const_line] = ACTIONS(47),
    [aux_sym_type_block_token1] = ACTIONS(47),
    [sym_type_line] = ACTIONS(47),
    [sym_text_line] = ACTIONS(47),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(49),
    [sym_package_line] = ACTIONS(51),
    [anon_sym_VARIABLES] = ACTIONS(51),
    [anon_sym_FUNCTIONS] = ACTIONS(51),
    [anon_sym_TYPES] = ACTIONS(51),
    [anon_sym_CONSTANTS] = ACTIONS(51),
    [anon_sym_DEPRECATED] = ACTIONS(51),
    [sym_func_line] = ACTIONS(51),
    [aux_sym_func_block_token1] = ACTIONS(51),
    [aux_sym_var_block_token1] = ACTIONS(51),
    [sym_var_line] = ACTIONS(51),
    [aux_sym_const_block_token1] = ACTIONS(51),
    [sym_const_line] = ACTIONS(51),
    [aux_sym_type_block_token1] = ACTIONS(51),
    [sym_type_line] = ACTIONS(51),
    [sym_text_line] = ACTIONS(51),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(53),
    [sym_package_line] = ACTIONS(55),
    [anon_sym_VARIABLES] = ACTIONS(55),
    [anon_sym_FUNCTIONS] = ACTIONS(55),
    [anon_sym_TYPES] = ACTIONS(55),
    [anon_sym_CONSTANTS] = ACTIONS(55),
    [anon_sym_DEPRECATED] = ACTIONS(55),
    [sym_func_line] = ACTIONS(55),
    [aux_sym_func_block_token1] = ACTIONS(55),
    [aux_sym_var_block_token1] = ACTIONS(55),
    [sym_var_line] = ACTIONS(55),
    [aux_sym_const_block_token1] = ACTIONS(55),
    [sym_const_line] = ACTIONS(55),
    [aux_sym_type_block_token1] = ACTIONS(55),
    [sym_type_line] = ACTIONS(55),
    [sym_text_line] = ACTIONS(55),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(57),
    [sym_package_line] = ACTIONS(59),
    [anon_sym_VARIABLES] = ACTIONS(59),
    [anon_sym_FUNCTIONS] = ACTIONS(59),
    [anon_sym_TYPES] = ACTIONS(59),
    [anon_sym_CONSTANTS] = ACTIONS(59),
    [anon_sym_DEPRECATED] = ACTIONS(59),
    [sym_func_line] = ACTIONS(59),
    [aux_sym_func_block_token1] = ACTIONS(59),
    [aux_sym_var_block_token1] = ACTIONS(59),
    [sym_var_line] = ACTIONS(59),
    [aux_sym_const_block_token1] = ACTIONS(59),
    [sym_const_line] = ACTIONS(59),
    [aux_sym_type_block_token1] = ACTIONS(59),
    [sym_type_line] = ACTIONS(59),
    [sym_text_line] = ACTIONS(59),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(61),
    [sym_package_line] = ACTIONS(63),
    [anon_sym_VARIABLES] = ACTIONS(63),
    [anon_sym_FUNCTIONS] = ACTIONS(63),
    [anon_sym_TYPES] = ACTIONS(63),
    [anon_sym_CONSTANTS] = ACTIONS(63),
    [anon_sym_DEPRECATED] = ACTIONS(63),
    [sym_func_line] = ACTIONS(63),
    [aux_sym_func_block_token1] = ACTIONS(63),
    [aux_sym_var_block_token1] = ACTIONS(63),
    [sym_var_line] = ACTIONS(63),
    [aux_sym_const_block_token1] = ACTIONS(63),
    [sym_const_line] = ACTIONS(63),
    [aux_sym_type_block_token1] = ACTIONS(63),
    [sym_type_line] = ACTIONS(63),
    [sym_text_line] = ACTIONS(63),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(65),
    [sym_package_line] = ACTIONS(67),
    [anon_sym_VARIABLES] = ACTIONS(67),
    [anon_sym_FUNCTIONS] = ACTIONS(67),
    [anon_sym_TYPES] = ACTIONS(67),
    [anon_sym_CONSTANTS] = ACTIONS(67),
    [anon_sym_DEPRECATED] = ACTIONS(67),
    [sym_func_line] = ACTIONS(67),
    [aux_sym_func_block_token1] = ACTIONS(67),
    [aux_sym_var_block_token1] = ACTIONS(67),
    [sym_var_line] = ACTIONS(67),
    [aux_sym_const_block_token1] = ACTIONS(67),
    [sym_const_line] = ACTIONS(67),
    [aux_sym_type_block_token1] = ACTIONS(67),
    [sym_type_line] = ACTIONS(67),
    [sym_text_line] = ACTIONS(67),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(69),
    [sym_package_line] = ACTIONS(71),
    [anon_sym_VARIABLES] = ACTIONS(71),
    [anon_sym_FUNCTIONS] = ACTIONS(71),
    [anon_sym_TYPES] = ACTIONS(71),
    [anon_sym_CONSTANTS] = ACTIONS(71),
    [anon_sym_DEPRECATED] = ACTIONS(71),
    [sym_func_line] = ACTIONS(71),
    [aux_sym_func_block_token1] = ACTIONS(71),
    [aux_sym_var_block_token1] = ACTIONS(71),
    [sym_var_line] = ACTIONS(71),
    [aux_sym_const_block_token1] = ACTIONS(71),
    [sym_const_line] = ACTIONS(71),
    [aux_sym_type_block_token1] = ACTIONS(71),
    [sym_type_line] = ACTIONS(71),
    [sym_text_line] = ACTIONS(71),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(73),
    [sym_package_line] = ACTIONS(75),
    [anon_sym_VARIABLES] = ACTIONS(75),
    [anon_sym_FUNCTIONS] = ACTIONS(75),
    [anon_sym_TYPES] = ACTIONS(75),
    [anon_sym_CONSTANTS] = ACTIONS(75),
    [anon_sym_DEPRECATED] = ACTIONS(75),
    [sym_func_line] = ACTIONS(75),
    [aux_sym_func_block_token1] = ACTIONS(75),
    [aux_sym_var_block_token1] = ACTIONS(75),
    [sym_var_line] = ACTIONS(75),
    [aux_sym_const_block_token1] = ACTIONS(75),
    [sym_const_line] = ACTIONS(75),
    [aux_sym_type_block_token1] = ACTIONS(75),
    [sym_type_line] = ACTIONS(75),
    [sym_text_line] = ACTIONS(75),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(79), 1,
      anon_sym_RBRACE,
    STATE(17), 1,
      aux_sym_func_block_repeat1,
    ACTIONS(77), 2,
      aux_sym_func_block_token3,
      aux_sym_func_block_token4,
  [11] = 3,
    ACTIONS(83), 1,
      anon_sym_RPAREN,
    STATE(22), 1,
      aux_sym_var_block_repeat1,
    ACTIONS(81), 2,
      aux_sym_func_block_token4,
      aux_sym_var_block_token2,
  [22] = 3,
    ACTIONS(87), 1,
      anon_sym_RPAREN,
    STATE(16), 1,
      aux_sym_var_block_repeat1,
    ACTIONS(85), 2,
      aux_sym_func_block_token4,
      aux_sym_var_block_token2,
  [33] = 3,
    ACTIONS(91), 1,
      anon_sym_RPAREN,
    STATE(18), 1,
      aux_sym_var_block_repeat1,
    ACTIONS(89), 2,
      aux_sym_func_block_token4,
      aux_sym_var_block_token2,
  [44] = 3,
    ACTIONS(95), 1,
      anon_sym_RBRACE,
    STATE(21), 1,
      aux_sym_func_block_repeat1,
    ACTIONS(93), 2,
      aux_sym_func_block_token3,
      aux_sym_func_block_token4,
  [55] = 3,
    ACTIONS(100), 1,
      anon_sym_RPAREN,
    STATE(18), 1,
      aux_sym_var_block_repeat1,
    ACTIONS(97), 2,
      aux_sym_func_block_token4,
      aux_sym_var_block_token2,
  [66] = 3,
    ACTIONS(102), 1,
      anon_sym_RBRACE,
    STATE(21), 1,
      aux_sym_func_block_repeat1,
    ACTIONS(93), 2,
      aux_sym_func_block_token3,
      aux_sym_func_block_token4,
  [77] = 3,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    STATE(19), 1,
      aux_sym_func_block_repeat1,
    ACTIONS(104), 2,
      aux_sym_func_block_token3,
      aux_sym_func_block_token4,
  [88] = 3,
    ACTIONS(111), 1,
      anon_sym_RBRACE,
    STATE(21), 1,
      aux_sym_func_block_repeat1,
    ACTIONS(108), 2,
      aux_sym_func_block_token3,
      aux_sym_func_block_token4,
  [99] = 3,
    ACTIONS(113), 1,
      anon_sym_RPAREN,
    STATE(18), 1,
      aux_sym_var_block_repeat1,
    ACTIONS(89), 2,
      aux_sym_func_block_token4,
      aux_sym_var_block_token2,
  [110] = 1,
    ACTIONS(115), 1,
      ts_builtin_sym_end,
  [114] = 1,
    ACTIONS(117), 1,
      aux_sym_func_block_token2,
  [118] = 1,
    ACTIONS(119), 1,
      aux_sym_func_block_token2,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(13)] = 0,
  [SMALL_STATE(14)] = 11,
  [SMALL_STATE(15)] = 22,
  [SMALL_STATE(16)] = 33,
  [SMALL_STATE(17)] = 44,
  [SMALL_STATE(18)] = 55,
  [SMALL_STATE(19)] = 66,
  [SMALL_STATE(20)] = 77,
  [SMALL_STATE(21)] = 88,
  [SMALL_STATE(22)] = 99,
  [SMALL_STATE(23)] = 110,
  [SMALL_STATE(24)] = 114,
  [SMALL_STATE(25)] = 118,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_block, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_block, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_block, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_const_block, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_block, 4, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_block, 4, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_block, 4, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func_block, 4, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_block, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func_block, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_block, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_block, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_block, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_block, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_block, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_const_block, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_var_block_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_var_block_repeat1, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [108] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_func_block_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_func_block_repeat1, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [115] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_godoc(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "godoc",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
